name: Publish preview on Develop
on:
  push:
    branches:
      - develop
jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    environment: preview
    params:
      branch: ${{ github.ref_name || "test" }}
