name: Publish preview update
on:
  push:
    branches:
      - "*"
jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      channel: preview
      env:
        APP_ENV: preview
        API_URL: https://preview-api.example.com
