name: Publish preview update
on:
  push:
    branches:
      - "*"
jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    environment: ${{ github.ref_name == 'main' && 'development' || 'preview' }}
    params:
      branch: ${{ github.ref_name || "test" }}
